[build-system]
requires = ['setuptools<65.6.0',
            'setuptools_scm',
            'wheel',
            'cython>=0.29.30',
            'oldest-supported-numpy',
            'extension-helpers']
build-backend = 'setuptools.build_meta'
